# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

#    - name: Build with Gradle
#      run: ./gradlew bootBuildImage
    - name: Clean & Build with Gradle
      run: ./gradlew clean build
#    - uses: eskatos/gradle-command-action@v1
#      with:
#        arguments: build
#      id: gradle

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Docker Build
      run: |
        docker build -t tesung30/myspring:latest .

    - name: Docker push
      run: |
        docker push tesung30/myspring:latest

#    - name: Build and push
#      id: docker_build
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        tags: tesung30/myspring:latest
#        push: true

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DDTHH-mm-ss
        utcOffset: "+09:00"

    - name: Show Current Time
      run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
      shell: bash
